### ISSUE TITLE
The GPU

### ISSUE THREAD

**Issue by xiehousen** [MarvinChung/Orbeez-SLAM#4]
Great job.

How much GPU memory is required to run the program?

**Comment by MarvinChung** [comment]
It depends on your scene, for TUM dataset 11G (RT 2080ti) is enough. However, older GPU type might cause some effect in rendering (see this #3 ).

**Comment by xiehousen** [comment]
Thanks a lot for your reply. @MarvinChung 

After replacing the computer, I finally ran your code successfully. Very good work.

I also have a question, like the picture you posted in the issue [](https://github.com/MarvinChung/Orbeez-SLAM/issues/3#issuecomment-1407651210), why there are many scattered points instead of just including the desk?

**Comment by xiehousen** [comment]
What I'm talking about is the part in the red box.
![2023-02-10 11-12-34 的屏幕截图](https://user-images.githubusercontent.com/37787619/217991520-297fb2cf-a896-4973-ad43-62e2bc34f5f1.png)

**Comment by MarvinChung** [comment]
Hi @xiehousen,
If you mean the blurry clouds in the visualization, it is called floaters in NeRF. It is a kind of defective feature in NeRF. There are some NeRF papers try to solve that. 

If you mean the background in NeRF, the code considers the background and will render it out.

To render the desk only, you need to manually use the crop aabb in the gui panel. The result may look like this:
![image](https://user-images.githubusercontent.com/22186310/217993839-a735f894-2d28-4459-bf22-7e747d5a61df.png)

**Comment by xiehousen** [comment]
Thank you very much for your reply.  

What I want to say is the floaters  in NeRF.
