### ISSUE TITLE
gpu memory

### ISSUE THREAD

**Issue by mtk380** [MarvinChung/Orbeez-SLAM#8]
Thanks for your work!  I am interested in how much memory you use in RTX3090?

**Comment by MarvinChung** [comment]
Hello, I'm currently unable to recall the exact amount of GPU memory required by the RTX 3090, as I don't currently possess one. However, I can confirm that I am able to run tum3 using my RTX 2080Ti.

**Comment by jeff999955** [comment]
@MarvinChung As I recall I could run it on my 8 GB 3070 Ti and the memory consumption was around 6 GB; can't remember the precise number though. 

@mtk380 You can adjust the number of sampled ray to reduce the memory usage.
